# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.Ï
name: muiscq

description: > # this means to ignore newlines until "baseurl:"
  But how could you live without a story to tell?

author:
  email:            liang.kui@hotmail.com
  github:           muiscq
  facebook:         ""
  youtubeUser:      ""
  youtubeChannel:   ""
  twitter:          ""
  stackoverflow:    ""
  quora:            ""
  linkedin:         ""
  pinterest:        ""
  googlePlus:       ""
  instagram:        ""
  reddit:           ""
  medium:           ""
  tumblr:           ""

copyright:
  year:             2017
  name:             musicq

# Google-analytics
google-analytics:
  id:               UA-61806273-1

# Disqus
disqus:
  id:               musicq

# URL
url:                "" # the base hostname & protocol for your site
baseurl:            "" # the subpath of your site, e.g. /blog
imgurl:             /images/post-imgs/ # base imgurl

permalink:          /:year-:month-:day/:title/

# Pagination
paginate:           10
paginate_path:      /page:num/

# Markdown
markdown:           kramdown
kramdown:
  input:            GFM

# Navigation
nav:
  - name:           "关于"
    url:            "/about"
  - name:           "归档"
    url:            "/archive"
  - name:           "标签"
    url:            "/tags"
  - name:           "github"
    url:            "https://github.com/musicq"

# Sass
sass:
  sass_dir:         _sass
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
plugins_dir:
  # - jekyll-admin
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-feed

exclude:            [vendor]